import { supabase } from './supabase-client.js';
const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const esc = (v='') => String(v).replace(/[&<>'"]/g, c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n||0));
const uid = (p='ID') => `${p}-${Math.random().toString(36).slice(2,7).toUpperCase()}${Date.now().toString().slice(-3)}`;
const todayISO = () => new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const niceDate = (d=todayISO()) => new Date(`${d}T12:00:00`).toLocaleDateString('en-US',{day:'2-digit',month:'short',year:'numeric'});

const demoState = {
  session:null,
  students:[
    {
      id:'ST-1048',name:'Zain Ali',avatar:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80',email:'zain@mugheeseditor.pk',password:'',phone:'0300 1234567',status:'Active Creator',program:'Hypic + CapCut',joinDate:'2026-08-14',
      today:8.75,week:66.79,month:223.21,lifetime:659.29,available:44.64,paid:614.65,attendance:91,progress:82,tasksDone:16,tasksTotal:20,trendParticipation:11,performance:'Very Good',
      payoutMethod:'JazzCash',payoutAccount:'0300 1234567',city:'Lahore',bio:'Learning creator workflows and short-form content systems.'
    },
    {
      id:'ST-1052',name:'Ayesha Noor',avatar:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80',email:'ayesha@mugheeseditor.pk',password:'',phone:'0312 5550099',status:'Active Creator',program:'TikTok Growth + Hypic',joinDate:'2026-08-22',
      today:6.43,week:47.32,month:174.64,lifetime:455.00,available:30.00,paid:425.00,attendance:96,progress:88,tasksDone:18,tasksTotal:20,trendParticipation:16,performance:'Excellent',
      payoutMethod:'Easypaisa',payoutAccount:'0312 5550099',city:'Islamabad',bio:'Short-form creator focused on face-led trend education.'
    }
  ],
  courses:[
    {id:'C-101',title:'TikTok Growth & Content Creation',type:'Live + Recorded',lessons:8,progressBy:{'ST-1048':82,'ST-1052':91},desc:'Filters, effects, hooks, lighting, CapCut editing, growth strategy and transition into value-led content.',cover:'tiktok',modules:['Account & Profile Setup','Trending Filters & Effects','Strong Hooks','CapCut Free Editing','Lighting & Framing','Posting & Analytics','Voice Content Transition','Personal Brand Expansion']},
    {id:'C-202',title:'Hypic + CapCut Creator Program',type:'Live + Weekly Updates',lessons:10,progressBy:{'ST-1048':67,'ST-1052':74},desc:'Face and faceless workflows, trend execution, reusable editing systems and future creator-app onboarding.',cover:'creator',modules:['Program Overview','Account Setup','Trend Research','Face Content Workflow','Faceless Workflow','CapCut Editing','Hypic Workflow','Upload Checklist','Common Mistakes','Weekly Opportunity Updates']}
  ],
  classes:[
    {id:'CL-201',title:'TikTok Filters: Hook + Creator Layout',trainer:'Mughees',date:'2026-09-25',time:'8:00 PM',batch:'TikTok Batch 01',status:'Upcoming',link:'#'},
    {id:'CL-202',title:'Hypic Trend Workflow — Live Practical',trainer:'Mughees',date:'2026-09-28',time:'8:30 PM',batch:'Creator Batch 02',status:'Upcoming',link:'#'},
    {id:'CL-190',title:'CapCut Editing: Fast Mobile Workflow',trainer:'Mughees',date:'2026-09-18',time:'8:00 PM',batch:'Creator Batch 02',status:'Recorded',link:'#'}
  ],
  trends:[
    {id:'TR-1',program:'TikTok',title:'AI Portrait Filter — Face + Center Layout',added:'2026-09-22',difficulty:'Easy',status:'New'},
    {id:'TR-2',program:'Hypic',title:'Cinematic Photo Motion Template',added:'2026-09-21',difficulty:'Easy',status:'New'},
    {id:'TR-3',program:'CapCut',title:'Beat Cut + Spotlight Reveal',added:'2026-09-19',difficulty:'Medium',status:'Active'}
  ],
  earnings:[
    {id:'E-1',studentId:'ST-1048',date:'2026-09-23',program:'Hypic',amount:8.75,note:'Approved creator payout credit'},
    {id:'E-2',studentId:'ST-1048',date:'2026-09-18',program:'CapCut',amount:17.50,note:'Approved creator payout credit'},
    {id:'E-3',studentId:'ST-1048',date:'2026-09-14',program:'Hypic',amount:25.00,note:'Approved creator payout credit'},
    {id:'E-4',studentId:'ST-1052',date:'2026-09-23',program:'TikTok Creator',amount:6.43,note:'Approved creator payout credit'},
    {id:'E-5',studentId:'ST-1048',date:'2026-09-20',program:'TikTok Creator',amount:15.54,note:'Approved creator payout credit'},
    {id:'E-6',studentId:'ST-1048',date:'2026-09-02',program:'Hypic',amount:156.42,note:'Approved creator payout credit'},
    {id:'E-7',studentId:'ST-1048',date:'2026-08-14',program:'Creator Program',amount:436.08,note:'Approved creator payout credit'},
    {id:'E-8',studentId:'ST-1052',date:'2026-08-22',program:'Creator Program',amount:448.57,note:'Approved creator payout credit'}
  ],
  withdrawals:[
    {id:'WD-1081',studentId:'ST-1048',date:'2026-09-14',amount:25.00,method:'JazzCash',account:'0300 1234567',status:'Paid',paidDate:'2026-09-14',reference:'JC-582914'},
    {id:'WD-1039',studentId:'ST-1048',date:'2026-09-07',amount:35.00,method:'Easypaisa',account:'0300 1234567',status:'Paid',paidDate:'2026-09-07',reference:'EP-414229'}
  ],
  notifications:[
    {id:'N-1',studentId:'ST-1048',date:'2026-09-23',title:'New earnings added',body:'A new approved earning has been added to your account.',read:false},
    {id:'N-2',studentId:'ST-1048',date:'2026-09-22',title:'New TikTok trend',body:'AI Portrait Filter tutorial is now available in Trend Updates.',read:false},
    {id:'N-3',studentId:'ST-1048',date:'2026-09-18',title:'Recording uploaded',body:'CapCut Editing: Fast Mobile Workflow recording is available.',read:true}
  ],
  programs:[
    {id:'PG-1',name:'Hypic Creator Workflow',code:'HY',desc:'Face and faceless creator workflows, trend execution and weekly updates.',status:'Active'},
    {id:'PG-2',name:'CapCut Creator Workflow',code:'CC',desc:'Mobile editing, creator layouts and repeatable content systems.',status:'Active'},
    {id:'PG-3',name:'TikTok Growth',code:'TT',desc:'Hooks, filters, lighting, posting and analytics workflows.',status:'Active'}
  ],
  supportMessages:[],
  contactMessages:[],
  admin:{email:'admin@mugheeseditor.pk',password:'',name:'Platform Admin'},
  settings:{brand:'Mughees Edtior',supportEmail:'support@mugheeseditor.pk',supportWhatsApp:'+92 300 0000000',weeklyUpdateText:'Creator earning updates are posted after the latest partner/program report becomes available.'}
};
const SCHEMA_VERSION = 3;

// Merge demo student accounts into saved state, preserving other fields
function mergeDemoAccounts(saved) {
  const demoStudents = demoState.students;
  const merged = (saved?.students || []).map(s => {
    const demo = demoStudents.find(d => d.id === s.id);
    if (demo) {
      // enforce canonical email/password, keep other fields
      return { ...s, email: demo.email, password: demo.password };
    }
    return s;
  });
  // add any missing demo students
  demoStudents.forEach(d => {
    if (!merged.find(s => s.id === d.id)) merged.push(d);
  });
  return merged;
}

function loadState() {
  try {
    const saved = localStorage.getItem('me_creator_state_v2');
    if (saved) {
      const x = JSON.parse(saved);
      const students = mergeDemoAccounts(x);
      const admin = demoState.admin; // canonical admin credentials
      const settings = { ...demoState.settings, ...(x.settings || {}) };
      return { ...demoState, ...x, students, admin, settings };
    }
  } catch (e) {}
  return structuredClone(demoState);
}
let state=loadState();
let dashView='overview';
let adminView='overview';
function save(){localStorage.setItem('me_creator_state_v2',JSON.stringify(state));}
function resetDemo(){localStorage.removeItem('me_creator_state_v2');state=structuredClone(demoState);save();location.hash='#/';render();toast('Local data reset.');}
function currentStudent(){return state.students.find(s=>s.id===state.session?.studentId) || state.students[0];}
function earningSummary(studentId){
  const rows=state.earnings.filter(e=>e.studentId===studentId);
  const now=new Date(todayISO()+'T23:59:59');
  const sumSince=days=>rows.filter(e=>{const d=new Date(e.date+'T12:00:00');return (now-d)<=days*86400000 && d<=now;}).reduce((a,e)=>a+Number(e.amount||0),0);
  const today=rows.filter(e=>e.date===todayISO()).reduce((a,e)=>a+Number(e.amount||0),0);
  return {today,week:sumSince(7),month:sumSince(30),lifetime:rows.reduce((a,e)=>a+Number(e.amount||0),0)};
}
function notify(studentId,title,body){state.notifications.unshift({id:uid('N'),studentId,date:todayISO(),title,body,read:false});save();}
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;$('#toastRoot').append(el);setTimeout(()=>el.remove(),3200);}

const icons={
  learn:'📚',live:'🎥',trend:'🔥',earn:'💰',growth:'📈',edit:'✂️',light:'💡',phone:'📱',bell:'🔔',wallet:'👛',shield:'🛡️',chart:'📊'
};

function heroCTAs(){
  if(state.session?.role==='student'){
    return `<div class="hero-actions"><a class="btn primary" href="#/dashboard">Go to Dashboard</a><a class="btn ghost" href="#/courses">Explore Courses</a></div>`;
  }else if(state.session?.role==='admin'){
    return `<div class="hero-actions"><a class="btn primary" href="#/admin">Admin Dashboard</a><a class="btn ghost" href="#/">View Website</a></div>`;
  }
  return `<div class="hero-actions"><button class="btn primary" data-action="open-signup">Start Learning</button><button class="btn ghost" data-action="open-login">Student Login</button></div>`;
}

function headerHero(){return `
<section class="hero premium-hero">
  <div class="hero-grid">
    <div class="hero-copy">
      <span class="eyebrow"><span class="dot"></span> Creator skills • Live mentorship • Personal dashboard</span>
      <h1>Build creator skills.<br><span class="gradient-text">Turn progress into opportunity.</span></h1>
      <p>A premium learning platform for TikTok growth, CapCut, Hypic and modern creator workflows — with live classes, trend updates, progress tracking and a private dashboard.</p>
      ${heroCTAs()}
      <div class="hero-proof">
        <div class="proof-faces"><img src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=80" alt="Creator"><img src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80" alt="Creator"><img src="https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=100&q=80" alt="Creator"></div>
        <div><strong>Practical creator community</strong><small>Live training • Weekly opportunities • Personal dashboard</small></div>
      </div>
    </div>
    <div class="hero-visual">
      <div class="creator-photo-card">
        <img src="assets/images/hero-creator.webp" alt="Young creator editing content in a professional studio workspace">
        <div class="photo-gradient"></div>
        <div class="mentor-label"><span class="live-dot"></span><div><strong>Learn with a clear system</strong><small>Classes, tasks, trends &amp; progress in one place</small></div></div>
      </div>
      <div class="hero-platform-stats">
        <div class="hps-card hps-wide">
          <span class="hps-icon">📚</span>
          <div class="hps-body"><strong class="hps-value">4</strong><span class="hps-label">Creator Skill Tracks</span><small class="hps-sub">TikTok · CapCut · Hypic · Editing</small></div>
        </div>
        <div class="hps-card">
          <span class="hps-icon">🎥</span>
          <div class="hps-body"><strong class="hps-value">Weekly</strong><span class="hps-label">Live Sessions</span></div>
        </div>
        <div class="hps-card">
          <span class="hps-icon">⏰</span>
          <div class="hps-body"><strong class="hps-value">24/7</strong><span class="hps-label">Learning Access</span></div>
        </div>
        <div class="hps-card hps-accent">
          <span class="hps-icon">🔥</span>
          <div class="hps-body"><strong class="hps-value">Live</strong><span class="hps-label">Trend Updates</span><small class="hps-sub">Fresh creator opportunities</small></div>
        </div>
      </div>
    </div>
  </div>
</section>`}

function homePage(){return `${headerHero()}
<div class="stats-row"><div class="stats-panel"><div class="stat"><strong>2</strong><span>Core training tracks</span></div><div class="stat"><strong>Live</strong><span>Practical instructor sessions</span></div><div class="stat"><strong>Weekly</strong><span>Creator trend updates</span></div><div class="stat"><strong>1:1</strong><span>Personal student dashboard</span></div></div></div>
<section class="section"><div class="section-head"><span class="kicker">What students learn</span><h2>Start with growth. Build real creator skills.</h2><p>The platform stays focused: first students learn a repeatable TikTok growth workflow, then they use the same editing and presentation skills across creator programs and future apps.</p></div><div class="cards"><div class="card"><div class="icon-tile">${icons.growth}</div><h3>TikTok Growth</h3><p>Filters, effects, hooks, framing, lighting, posting and analytics — taught as a practical system.</p></div><div class="card"><div class="icon-tile">${icons.edit}</div><h3>CapCut Editing</h3><p>Fast mobile editing without requiring CapCut Pro: cuts, text, pacing, overlays and clean creator layouts.</p></div><div class="card"><div class="icon-tile">${icons.trend}</div><h3>Creator Programs</h3><p>Hypic, CapCut and future apps can be added from the admin panel without rebuilding the website.</p></div></div></section>
<section class="section alt"><div class="inner"><div class="section-head"><span class="kicker">Courses</span><h2>Two clear learning paths</h2><p>No confusing affiliate bundles. Students join training, attend live classes, watch recordings and follow updates inside their own account.</p></div><div class="cards">${state.courses.map(courseCard).join('')}</div></div></section>
<section class="section"><div class="section-head"><span class="kicker">How it works</span><h2>A simple student journey</h2></div><div class="steps"><div class="step"><span class="step-num">01</span><h3>Create Account</h3><p>Each student gets a private profile and personal dashboard.</p></div><div class="step"><span class="step-num">02</span><h3>Learn Live</h3><p>Join scheduled classes, watch recordings and complete practical tasks.</p></div><div class="step"><span class="step-num">03</span><h3>Follow Trends</h3><p>New TikTok, Hypic, CapCut and future-app updates appear inside the dashboard.</p></div><div class="step"><span class="step-num">04</span><h3>Track Progress</h3><p>Performance, approved earnings, available balance and payments stay organized in one place.</p></div></div></section>
<section class="section alt"><div class="inner"><div class="program-grid"><div class="program-feature"><span class="kicker" style="color:#a7f3ff">Future-ready system</span><h3>Add the next creator app without rebuilding the platform.</h3><p>Admin can publish a new program, tutorials, eligibility notes and trend updates from one control panel. Students see new opportunities in the same familiar dashboard.</p><div class="chip-row"><span class="chip">Hypic</span><span class="chip">CapCut</span><span class="chip">TikTok</span><span class="chip">Future Apps</span></div></div><div class="program-list">${state.trends.map(t=>`<div class="program-item"><div class="left"><div class="program-logo">${t.program.slice(0,2)}</div><div><strong>${esc(t.program)}</strong><small style="display:block;color:#7b8798;margin-top:3px">${esc(t.title)}</small></div></div><span class="tag ${t.status==='New'?'green':''}">${esc(t.status)}</span></div>`).join('')}</div></div></div></section>
<section class="section"><div class="section-head"><span class="kicker">Live training</span><h2>Class, recording, notes — all connected</h2></div><div class="live-grid">${state.classes.slice(0,2).map(c=>`<div class="live-card"><span class="live-badge">UPCOMING</span><h3 style="margin-top:14px">${esc(c.title)}</h3><p style="color:#6e7a8d">${niceDate(c.date)} · ${esc(c.time)} · ${esc(c.trainer)}</p><button class="btn primary" data-action="open-signup">Join the platform</button></div>`).join('')}</div></section>
<section class=\"feature-promo-banner\"><div class=\"fpb-inner\"><span class=\"fpb-pulse\"></span><span class=\"fpb-text\">🎓 Recorded lessons now available — <strong>start learning today</strong></span><span class=\"fpb-arrow\">→</span></div></section><section class=\"feature-section\"><div class=\"fs-inner\"><div class=\"fs-left\"><span class=\"fs-eyebrow\">✨ Premium Creator Learning</span><h2 class=\"fs-heading\">Learn creator skills in a more <span class=\"gradient-text\">organized, structured</span> way.</h2><p class=\"fs-para\">Students get one premium workspace for recorded lessons, weekly Q&amp;A support, WhatsApp community, creator trends, progress tracking, approved earnings and payment history — all in one place.</p><div class=\"fs-checklist\"><div class=\"fs-check\"><span class=\"fs-check-icon\">📹</span><span>Structured recorded modules</span></div><div class=\"fs-check\"><span class=\"fs-check-icon\">🎙️</span><span>Weekly Q&amp;A support session</span></div><div class=\"fs-check\"><span class=\"fs-check-icon\">💬</span><span>WhatsApp group support</span></div><div class=\"fs-check\"><span class=\"fs-check-icon\">📊</span><span>Dashboard, earnings &amp; payment tracking</span></div></div><div class=\"fs-ctas\">${heroCTAs()}</div></div><div class=\"fs-right\"><div class=\"fs-img-wrap\"><img src=\"assets/images/feature-creator.webp\" alt=\"Student learning creator skills in a premium dark workspace\" class=\"fs-main-img\"><div class=\"fs-img-overlay\"></div></div><div class=\"fsc fsc-top-left\"><span class=\"fsc-icon\">📹</span><div><strong>Recorded Lessons</strong><small>Learn at your own pace</small></div></div><div class=\"fsc fsc-top-right\"><span class=\"fsc-icon\">🔥</span><div><strong>Creator Trends</strong><small>Weekly updates</small></div></div><div class=\"fsc fsc-bottom\"><div class=\"fsc-row\"><span class=\"fsc-pill fsc-pill-violet\">🎥 4 Skill Tracks</span><span class=\"fsc-pill fsc-pill-cyan\">⏰ 24/7 Access</span><span class=\"fsc-pill fsc-pill-green\">💬 WhatsApp Support</span></div><div class=\"fsc-progress-card\"><div class=\"fsc-pc-head\"><span>Your progress</span><strong>82%</strong></div><div class=\"fsc-bar\"><div class=\"fsc-bar-fill\" style=\"width:82%\"></div></div><small>TikTok Growth Track</small></div></div></div></div></section><section class=\"section alt\"><div class=\"inner\"><div class=\"section-head\"><span class=\"kicker\">Trust &amp; clarity</span><h2>Built around training, not referrals.</h2><p>The student dashboard is designed around course progress, creator performance, recorded lessons, weekly Q&amp;A, trend updates and approved payout credits. There is no referral tree or affiliate-sales dashboard.</p></div></div></section>`}

function courseCard(c){return `<div class="card course-card"><div class="course-cover ${c.cover}"><div><span class="pill" style="background:rgba(255,255,255,.15);color:#fff">${esc(c.type)}</span><h3 style="margin:10px 0 0">${esc(c.title)}</h3></div></div><div class="course-body"><div class="course-meta"><span>${c.lessons} modules</span><span>Practical track</span></div><p>${esc(c.desc)}</p><a class="btn primary" href="#/courses" style="margin-top:16px">View Curriculum</a></div></div>`}

function pageHero(title,desc,chips=[]){return `<section class="page-hero"><div class="inner"><div class="chip-row">${chips.map(c=>`<span class="chip">${esc(c)}</span>`).join('')}</div><h1>${title}</h1><p>${desc}</p></div></section>`}

function coursesPage(){return `${pageHero('Courses built for practical creators.','Focused training paths with live classes, recordings, tasks and weekly creator updates.',['Live classes','Recordings','Practical tasks'])}<section class="section"><div class="cards">${state.courses.map(c=>`<div class="card course-card"><div class="course-cover ${c.cover}"><div><span class="pill" style="background:rgba(255,255,255,.15);color:#fff">${esc(c.type)}</span><h3 style="margin:10px 0 0">${esc(c.title)}</h3></div></div><div class="course-body"><p>${esc(c.desc)}</p><ul class="feature-list">${c.modules.map(m=>`<li>${esc(m)}</li>`).join('')}</ul><button class="btn primary" data-action="open-signup" style="margin-top:18px">Join & Access Dashboard</button></div></div>`).join('')}</div></section>`}

function programsPage(){return `${pageHero('Creator Programs','A modular program area for Hypic, CapCut, TikTok workflows and any new creator app you add later.',['Admin-manageable','Future-ready','Trend-driven'])}<section class="section"><div class="program-grid"><div class="program-feature"><span class="kicker" style="color:#a7f3ff">Current programs</span><h3>One dashboard. Multiple creator opportunities.</h3><p>Students do not need separate accounts for every training track. Admin can assign programs to each student and publish new lessons or trend updates as the ecosystem changes.</p></div><div class="program-list">${(state.programs||[]).map(p=>`<div class="program-item"><div class="left"><div class="program-logo">${esc(p.code||p.name.slice(0,2).toUpperCase())}</div><div><strong>${esc(p.name)}</strong><small style="display:block;color:#7b8798">${esc(p.desc)}</small></div></div><span class="tag green">${esc(p.status||'Active')}</span></div>`).join('')}</div></div></section>`}

function livePage(){return `${pageHero('Live Classes','Students see upcoming sessions, join links and recordings from their own dashboard.',['Zoom/Meet ready','Attendance','Recordings'])}<section class="section"><div class="live-grid">${state.classes.map(c=>`<div class="live-card"><span class="tag ${c.status==='Upcoming'?'orange':'green'}">${esc(c.status)}</span><h3 style="margin-top:14px">${esc(c.title)}</h3><p style="color:#6e7a8d">${niceDate(c.date)} · ${esc(c.time)}</p><p><strong>Trainer:</strong> ${esc(c.trainer)}<br><strong>Batch:</strong> ${esc(c.batch)}</p><button class="btn primary" data-action="open-signup">Student Login Required</button></div>`).join('')}</div></section>`}

function howPage(){return `${pageHero('How the platform works','A simple flow your client, admin team and students can understand at a glance.',['No affiliate system','Admin-controlled data','Private dashboards'])}<section class="section"><div class="steps"><div class="step"><span class="step-num">01</span><h3>Student signs up</h3><p>A private account is created. The student only sees their own courses, classes, performance and approved balance.</p></div><div class="step"><span class="step-num">02</span><h3>Admin assigns training</h3><p>Admin assigns TikTok Growth, Hypic, CapCut or a future creator program.</p></div><div class="step"><span class="step-num">03</span><h3>Student learns & creates</h3><p>Live classes, recordings, trend updates and practical creator tasks are delivered inside the dashboard.</p></div><div class="step"><span class="step-num">04</span><h3>Admin updates account</h3><p>Admin manages performance and adds approved payout credits. The student receives an automatic notification.</p></div></div></section><section class="section alt"><div class="inner"><div class="cards"><div class="card"><div class="icon-tile">💰</div><h3>Approved balance</h3><p>The student-facing balance is the amount approved and available for payout. Internal source calculations remain an administrative record.</p></div><div class="card"><div class="icon-tile">🏦</div><h3>Withdrawal request</h3><p>Students can request payout through JazzCash, Easypaisa, SadaPay, NayaPay or bank transfer.</p></div><div class="card"><div class="icon-tile">✅</div><h3>Admin marks paid</h3><p>After payment is sent, Admin records a reference and the transaction appears in the student's payment history.</p></div></div></div></section>`}

function faqPage(){const qs=[['Is this an affiliate or referral platform?','No. The platform is designed around training, creator programs, classes, performance tracking and managed payout credits.'],['Does every student get a separate dashboard?','Yes. Every account has its own private data, course progress, performance, classes, trends, balance and payment history.'],['Can new apps be added later?','Yes. Admin can add new creator programs and publish trend updates without redesigning the core website.'],['How are earnings shown?','The dashboard shows approved payout credits/available balance assigned to the student. It is not a public statement of the platform’s gross receipts or partner accounting.'],['Which payout methods are supported?','Supported payout methods include JazzCash, Easypaisa, SadaPay, NayaPay and bank transfer. USD balances can be settled through the configured payout workflow and applicable conversion process.'],['Are earnings guaranteed?','No. Earnings can vary by activity, third-party program rules, eligibility, performance and availability. The site should never promise guaranteed income.']];return `${pageHero('Frequently Asked Questions','Clear answers for students before they join.',['Training','Dashboard','Payouts'])}<section class="section"><div class="faq-list">${qs.map((q,i)=>`<div class="faq"><button data-faq="${i}"><span>${esc(q[0])}</span><span>+</span></button><div class="answer">${esc(q[1])}</div></div>`).join('')}</div></section>`}

function contactPage(){return `${pageHero('Contact & Support','Use this section for admissions, technical help and student support.',['Admissions','Technical support','Account help'])}<section class="section"><div class="contact-grid"><div class="card dark"><span class="kicker" style="color:#a7f3ff">Support</span><h2 style="font-size:36px">Need help?</h2><p>Use the official channels below for admissions, account help and payout support.</p><ul class="feature-list" style="margin-top:24px"><li style="color:#c5d3e5">Email: ${esc(state.settings.supportEmail)}</li><li style="color:#c5d3e5">WhatsApp: ${esc(state.settings.supportWhatsApp)}</li><li style="color:#c5d3e5">Support hours: set by Admin</li></ul></div><form class="form-card" id="contactForm"><div class="field"><label>Name</label><input required name="name" placeholder="Your name"></div><div class="field"><label>Email</label><input required type="email" name="email" placeholder="you@example.com"></div><div class="field"><label>Message</label><textarea required name="message" rows="6" placeholder="How can we help?"></textarea></div><button class="btn primary" type="submit">Send Message</button><p class="micro" style="margin-top:12px;color:#7b8798">Your message will be saved to the support inbox.</p></form></div></section>`}

const legalPages={
  terms:{title:'Terms & Conditions',intro:'These draft terms are a launch-ready starting point, but should be reviewed by a qualified lawyer for your exact company, country, tax and payout arrangements.',sections:[['1. Platform purpose','Mughees Edtior provides educational content, live classes, recordings, creator-program information, student performance tools and account-based payout records. The platform is not an employment agency, investment product or guaranteed-income scheme.'],['2. Accounts','Students must provide accurate information, protect login credentials and use only their own account. Admin may suspend accounts for fraud, abuse, impersonation, payment misuse or serious policy violations.'],['3. Courses and third-party apps','Course material may discuss TikTok, CapCut, Hypic or other tools. Third-party features, eligibility and program rules can change without notice. Students are responsible for complying with those platforms’ terms.'],['4. Earnings shown in the dashboard','Amounts shown as Approved Earnings or Available Balance are payout credits approved for the student account. They are not necessarily the same as gross revenue, partner receipts or other internal accounting amounts. Any material student-facing fees or conditions must be disclosed in the applicable policy before they are applied.'],['5. Payouts','Payouts are processed using supported methods and are subject to verification, fraud checks, provider availability and the Payout Policy. Never share OTPs or account passwords with staff.'],['6. No income guarantee','Training, trends and creator programs do not guarantee views, followers, acceptance into third-party programs or any specific income.'],['7. Intellectual property','Course videos, notes, branding and platform materials may not be copied, resold or redistributed without permission.'],['8. Changes','We may update courses, schedules, supported programs and platform features. Material policy changes should be communicated to users.']]},
  privacy:{title:'Privacy Policy',intro:'This policy describes the information the platform may collect and how it is handled.',sections:[['Information we collect','Account identity and contact details, course activity, attendance, performance records, payout-method details, withdrawal records, device/security data and support communications.'],['How information is used','To provide accounts and courses, schedule classes, manage student support, maintain performance records, process payout requests, prevent fraud and improve platform reliability.'],['Financial information','Store only the minimum payout information required. Do not store wallet PINs, OTPs, card CVVs or online banking passwords. Sensitive production data should be encrypted and access-controlled.'],['Sharing','Data may be shared with service providers necessary to operate the platform, such as hosting, email, analytics, live-class or payout providers, subject to appropriate agreements.'],['Retention and security','The platform uses defined retention periods, backups, access controls and security practices appropriate to the deployed service.'],['Your choices','Users should be able to request correction of inaccurate profile information and contact support about privacy requests, subject to applicable law.']]},
  'payout-policy':{title:'Payout Policy',intro:'This page defines what the dashboard balance means and how payout requests are handled.',sections:[['Approved Earnings','Student dashboards display amounts approved as payout credits for that student. The amount shown as Available Balance is the amount currently eligible to be requested, subject to account verification and any clearly disclosed conditions.'],['Supported methods','The platform may support JazzCash, Easypaisa, SadaPay, NayaPay and bank transfer. Availability can vary by account and provider.'],['Request process','The student selects a supported method, confirms account details and submits a request. The amount is reserved while the request is pending.'],['Processing','The platform aims to process valid requests promptly, but timing can vary due to verification, provider delays, holidays, technical issues or compliance checks. Do not promise a guaranteed timeline unless operations can consistently meet it.'],['Failed or rejected payouts','If a request is rejected or fails, the reserved amount should return to the student’s available balance unless there is a documented account restriction.'],['Transparency','Any fee, adjustment or condition that changes the amount a student is entitled to receive should be disclosed before the student confirms a withdrawal.']]},
  'refund-policy':{title:'Refund Policy',intro:'This policy explains how refund requests are handled for enrollment and digital access.',sections:[['Course enrollment','If you charge for enrollment, state the refund window clearly before payment. Avoid “no refund” wording unless it is lawful and appropriate for your delivery model.'],['Digital access','If substantial digital content or recordings are unlocked immediately, explain how that affects refund eligibility under applicable law.'],['Duplicate or failed payments','Duplicate charges and confirmed payment errors should be investigated and corrected.'],['How to request','Provide a support email, required information and a reasonable review timeline.']]},
  'earnings-policy':{title:'Earnings & Balance Policy',intro:'This policy separates student-visible approved payout credits from internal partner/platform accounting.',sections:[['Student-visible amount','The student dashboard shows Approved Earnings, Available Balance and Total Paid. These are the amounts credited to the student account by Admin.'],['Internal records','The platform may maintain separate internal records for partner reports, source receipts, operational costs or other accounting. Those internal records are not presented as student-owned balances.'],['Updates','Creator earning updates may be added after the relevant program report becomes available. Update timing can vary.'],['Corrections','If an approved credit was entered incorrectly, corrections should be logged with a reason and users should be notified when the correction materially changes their balance.'],['No guarantee','Historical earnings, examples or dashboard screenshots do not guarantee future earnings.']]},
  'earnings-disclaimer':{title:'Earnings Disclaimer',intro:'Creator and social-media outcomes vary substantially. This disclaimer should remain visible wherever earning examples are used.',sections:[['No guaranteed results','We do not guarantee views, followers, virality, third-party program approval, recurring work or a specific earning amount.'],['Third-party dependency','Creator opportunities may depend on external apps and programs that can change eligibility, rates, availability, policies or geographic access.'],['Examples','Screenshots, case studies and demonstrations are examples only and should be accurately labeled as demo, historical or representative where applicable.'],['Student responsibility','Students remain responsible for following platform rules, content policies, copyright requirements and applicable laws.']]},
  'community-guidelines':{title:'Community Guidelines',intro:'Keep live classes and student groups useful, respectful and safe.',sections:[['Respect','No harassment, threats, hate, bullying or targeted abuse.'],['Privacy','Do not share another student’s personal data, payout details, private messages or login information without permission.'],['Content integrity','Do not submit stolen work, impersonate another creator or intentionally violate third-party platform rules.'],['Class behavior','Avoid spam, disruptive behavior and unauthorized recording or redistribution of paid/private lessons.'],['Enforcement','Warnings, temporary restrictions or suspension may be used depending on severity.']]}
};
function legalPage(key){const p=legalPages[key];return `<div class="legal-wrap"><span class="kicker">Mughees Edtior · Legal</span><h1>${esc(p.title)}</h1><div class="legal-callout">Draft for product design purposes. Have a qualified local lawyer review the final version before taking real payments or processing real creator payouts.</div><p style="margin-top:24px">${esc(p.intro)}</p>${p.sections.map(s=>`<h2>${esc(s[0])}</h2><p>${esc(s[1])}</p>`).join('')}<p class="micro" style="margin-top:35px">Last updated: ${niceDate()}</p></div>`}

function authHTML(tab='login'){
 if(tab==='login')return `<h2>Welcome back</h2><p style="color:#728096">Login to your student or admin account.</p><form id="loginForm"><div class="field"><label>Email</label><input required type="email" name="email" placeholder="you@example.com"></div><div class="field"><label>Password</label><input required type="password" name="password" placeholder="••••••••"><a href="#" data-action="open-forgot-password" class="forgot-link" style="display:block;margin:8px 0;color:#3b82f6;text-align:center;font-size:0.9rem;">Forgot password?</a></div><button class="btn primary" style="width:100%" type="submit">Login</button></form>`;
 return `<h2>Create student account</h2><p style="color:#728096">Create your account to access courses, classes, progress and earnings.</p><form id="signupForm"><div class="field"><label>Full name</label><input required name="name" placeholder="Your name"></div><div class="field"><label>Email</label><input required type="email" name="email" placeholder="you@example.com"></div><div class="field"><label>Phone</label><input required name="phone" placeholder="03xx xxxxxxx"></div><div class="field"><label>Password</label><input required minlength="6" type="password" name="password" placeholder="Minimum 6 characters"></div><div class="field"><label>Program</label><select name="program"><option>TikTok Growth</option><option>Hypic + CapCut</option><option>TikTok Growth + Hypic</option></select></div><button class="btn primary" style="width:100%" type="submit">Create Account</button></form>`;
}

function openAuth(tab='login'){
 if(state.session?.role==='student'){closeModals();location.hash='#/dashboard';render();return;}
 if(state.session?.role==='admin'){closeModals();location.hash='#/admin';render();return;}
 $('#authModal').classList.add('open');$('#authModal').setAttribute('aria-hidden','false');$$('[data-auth-tab]').forEach(b=>b.classList.toggle('active',b.dataset.authTab===tab));$('#authBody').innerHTML=authHTML(tab);bindForms();
}

function openForgotPassword(){
  $('#authModal').classList.add('open');
  $('#authModal').setAttribute('aria-hidden','false');
  $('#authBody').innerHTML = `<h2>Reset password</h2><p style="color:#728096">Enter your email to receive a reset link.</p><form id="forgotPasswordForm"><div class="field"><label>Email</label><input required type="email" name="email" placeholder="you@example.com"></div><button class="btn primary" style="width:100%" type="submit">Send Reset Email</button></form>`;
  bindForms();
}

function openResetPassword(){
  $('#authModal').classList.add('open');
  $('#authModal').setAttribute('aria-hidden','false');
  $('#authBody').innerHTML = "<h2>Set new password</h2><p style=\"color:#728096\">Enter a new password (minimum 8 characters).</p><form id=\"resetPasswordForm\"><div class=\"field pw-wrap\"><label>New Password</label><input required minlength=\"8\" type=\"password\" name=\"password\" id=\"rp_pw\" placeholder=\"Minimum 8 characters\"><button type=\"button\" class=\"eye-btn\" data-action=\"toggle-eye\" data-target=\"rp_pw\" aria-label=\"Show/hide password\">👁</button></div><div class=\"field pw-wrap\"><label>Confirm Password</label><input required minlength=\"8\" type=\"password\" name=\"confirm\" id=\"rp_cf\" placeholder=\"Confirm new password\"><button type=\"button\" class=\"eye-btn\" data-action=\"toggle-eye\" data-target=\"rp_cf\" aria-label=\"Show/hide password\">👁</button></div><p id=\"rp_err\" style=\"color:#ef4444;font-size:12px;margin:0 0 8px\"></p><button class=\"btn primary\" style=\"width:100%\" type=\"submit\">Update Password</button></form>";
  bindForms();
}
function closeModals(){$$('.modal').forEach(m=>m.classList.remove('open'));}

function sparkline(values){const w=620,h=220,p=18,max=Math.max(...values),min=Math.min(...values),range=Math.max(1,max-min);const pts=values.map((v,i)=>`${p+i*((w-2*p)/(values.length-1))},${h-p-((v-min)/range)*(h-2*p)}`).join(' ');return `<svg class="earn-chart" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#8b5cf6" stop-opacity=".28"/><stop offset="1" stop-color="#22d3ee" stop-opacity="0"/></linearGradient><linearGradient id="line" x1="0" y1="0" x2="1" y2="0"><stop stop-color="#8b5cf6"/><stop offset="1" stop-color="#22d3ee"/></linearGradient></defs><polyline points="${pts} ${w-p},${h-p} ${p},${h-p}" fill="url(#area)" stroke="none"/><polyline points="${pts}" fill="none" stroke="url(#line)" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>${values.map((v,i)=>{const [x,y]=pts.split(' ')[i].split(',');return `<circle cx="${x}" cy="${y}" r="4" fill="#fff" stroke="#7c3aed" stroke-width="3"/>`}).join('')}</svg>`}

function studentSidebar(s){const items=[['overview','🏠 Dashboard'],['courses','📚 My Courses'],['live','🎥 Live Classes'],['trends','🔥 Trends'],['performance','📊 Performance'],['earnings','💰 Earnings'],['withdraw','🏦 Withdraw'],['payments','🧾 Payments'],['notifications','🔔 Notifications'],['profile','👤 Profile'],['support','💬 Support']];return `<aside class="sidebar"><div class="side-profile side-profile-rich">${s.avatar?`<img src="${esc(s.avatar)}" alt="">`:`<span class="side-avatar-fallback">${esc(s.name.split(' ').map(x=>x[0]).join('').slice(0,2))}</span>`}<div><strong>${esc(s.name)}</strong><small>${esc(s.id)} · ${esc(s.status)}</small></div></div><div class="side-nav">${items.map(([id,l])=>`<button class="${dashView===id?'active':''}" data-dash="${id}">${l}</button>`).join('')}<button data-action="logout">↩ Logout</button></div></aside>`}

function studentDashboard(){if(!state.session||state.session.role!=='student'){openAuth('login');location.hash='#/';return homePage()}const s=currentStudent();return `<div class="dashboard-page"><div class="dashboard-shell">${studentSidebar(s)}<section class="dashboard-main" id="dashContent">${studentView(s)}</section></div></div>`}
function studentView(s){
 if(dashView==='courses') return studentCourses(s);
 if(dashView==='live') return studentLive(s);
 if(dashView==='trends') return studentTrends(s);
 if(dashView==='performance') return studentPerformance(s);
 if(dashView==='earnings') return studentEarnings(s);
 if(dashView==='withdraw') return studentWithdraw(s);
 if(dashView==='payments') return studentPayments(s);
 if(dashView==='notifications') return studentNotifications(s);
 if(dashView==='profile') return studentProfile(s);
 if(dashView==='support') return studentSupport(s);
 const myE=state.earnings.filter(e=>e.studentId===s.id).slice(0,4);const myN=state.notifications.filter(n=>n.studentId===s.id).filter(n=>!n.read).length;const totals=earningSummary(s.id);
 return `<div class="dash-top"><div><h1>Welcome back, ${esc(s.name.split(' ')[0])} 👋</h1><p>${esc(s.id)} · ${esc(s.status)} · ${esc(s.program)}</p></div><div class="dash-actions"><button class="btn light" data-dash="notifications">🔔 ${myN}</button><button class="btn primary" data-dash="withdraw">Withdraw</button></div></div>
 <div class="dash-card-grid"><div class="dash-card"><small>Today's Earnings</small><strong>${money(totals.today)}</strong><div class="delta">Approved payout credit</div></div><div class="dash-card"><small>Last 7 Days</small><strong>${money(totals.week)}</strong><div class="delta">Recent activity</div></div><div class="dash-card"><small>Last 30 Days</small><strong>${money(totals.month)}</strong><div class="delta">Rolling total</div></div><div class="dash-card"><small>Total Earnings</small><strong>${money(totals.lifetime)}</strong><div class="delta">Approved history</div></div></div>
 <div class="dash-card-grid" style="margin-top:14px"><div class="dash-card"><small>Available Balance</small><strong style="color:#059669">${money(s.available)}</strong><div class="delta">Available to request</div></div><div class="dash-card"><small>Total Paid</small><strong>${money(s.paid)}</strong><div class="delta">Completed payouts</div></div><div class="dash-card"><small>Course Progress</small><strong>${s.progress}%</strong><div class="progress" style="margin-top:9px"><i style="width:${s.progress}%"></i></div></div><div class="dash-card"><small>Performance</small><strong>${esc(s.performance)}</strong><div class="delta">Attendance ${s.attendance}%</div></div></div>
 <div class="dashboard-grid"><div class="panel"><div class="panel-head"><h3>Earning activity</h3><div class="tabs"><button>1W</button><button class="active">1M</button><button>3M</button><button>1Y</button></div></div>${sparkline([12,20,15,31,28,41,36,56,49,62,58,71])}</div><div class="panel"><div class="panel-head"><h3>Next live class</h3><span class="tag orange">Upcoming</span></div>${nextClassCard()}</div></div>
 <div class="dashboard-grid"><div class="panel"><div class="panel-head"><h3>Recent earnings</h3><button class="btn small light" data-dash="earnings">View all</button></div><div class="list">${myE.map(e=>`<div class="list-item"><div class="meta"><strong>${esc(e.program)}</strong><small>${niceDate(e.date)}</small></div><span class="amount green">+ ${money(e.amount)}</span></div>`).join('')||'<div class="empty">No earnings yet.</div>'}</div></div><div class="panel"><div class="panel-head"><h3>Latest trends</h3><button class="btn small light" data-dash="trends">View</button></div><div class="list">${state.trends.slice(0,3).map(t=>`<div class="list-item"><div class="meta"><strong>${esc(t.program)}</strong><small>${esc(t.title)}</small></div><span class="tag ${t.status==='New'?'green':''}">${esc(t.status)}</span></div>`).join('')}</div></div></div>`
}
function nextClassCard(){const c=state.classes.find(x=>x.status==='Upcoming')||state.classes[0];return `<h3 style="margin:6px 0">${esc(c.title)}</h3><p style="color:#728096">${niceDate(c.date)} · ${esc(c.time)}<br>${esc(c.trainer)} · ${esc(c.batch)}</p><button class="btn primary" data-action="class-detail" data-id="${c.id}">Open Class</button>`}
function studentCourses(s){return `<div class="subpage-head"><div><h1>My Courses</h1><p style="color:#748195">Assigned training and course progress.</p></div></div><div class="cards">${state.courses.map(c=>{const p=c.progressBy[s.id]??0;return `<div class="card"><span class="pill">${esc(c.type)}</span><h3 style="margin-top:14px">${esc(c.title)}</h3><p>${esc(c.desc)}</p><div style="display:flex;justify-content:space-between;font-size:12px;margin:18px 0 7px"><span>Progress</span><strong>${p}%</strong></div><div class="progress"><i style="width:${p}%"></i></div><ul class="feature-list">${c.modules.slice(0,5).map(m=>`<li>${esc(m)}</li>`).join('')}</ul><button class="btn primary" data-action="course-detail" data-id="${c.id}">Continue Learning</button></div>`}).join('')}</div>`}
function studentLive(){return `<div class="subpage-head"><div><h1>Live Classes & Recordings</h1><p style="color:#748195">Upcoming sessions and previous recordings.</p></div></div><div class="live-grid">${state.classes.map(c=>`<div class="live-card"><span class="tag ${c.status==='Upcoming'?'orange':'green'}">${esc(c.status)}</span><h3 style="margin-top:14px">${esc(c.title)}</h3><p style="color:#748195">${niceDate(c.date)} · ${esc(c.time)}<br>${esc(c.trainer)} · ${esc(c.batch)}</p><button class="btn primary" data-action="class-detail" data-id="${c.id}">${c.status==='Upcoming'?'Join Class':'Watch Recording'}</button></div>`).join('')}</div>`}
function studentTrends(){return `<div class="subpage-head"><div><h1>Trend Updates</h1><p style="color:#748195">New creator trends published by Admin.</p></div></div><div class="cards">${state.trends.map(t=>`<div class="card"><div style="display:flex;justify-content:space-between"><span class="pill">${esc(t.program)}</span><span class="tag ${t.status==='New'?'green':''}">${esc(t.status)}</span></div><h3 style="margin-top:16px">${esc(t.title)}</h3><p>Difficulty: ${esc(t.difficulty)} · Added ${niceDate(t.added)}</p><button class="btn primary" data-action="trend-detail" data-id="${t.id}">View Tutorial</button></div>`).join('')}</div>`}
function studentPerformance(s){return `<div class="subpage-head"><div><h1>Performance</h1><p style="color:#748195">Your learning and participation summary.</p></div></div><div class="dash-card-grid"><div class="dash-card"><small>Course Progress</small><strong>${s.progress}%</strong><div class="progress" style="margin-top:9px"><i style="width:${s.progress}%"></i></div></div><div class="dash-card"><small>Attendance</small><strong>${s.attendance}%</strong><div class="progress" style="margin-top:9px"><i style="width:${s.attendance}%"></i></div></div><div class="dash-card"><small>Tasks Completed</small><strong>${s.tasksDone}/${s.tasksTotal}</strong><div class="delta">Practical assignments</div></div><div class="dash-card"><small>Trend Participation</small><strong>${s.trendParticipation}</strong><div class="delta">Creator updates completed</div></div></div><div class="dashboard-grid"><div class="panel"><h3>Performance level</h3><h2 style="font-size:44px;margin:18px 0 8px">${esc(s.performance)}</h2><p style="color:#748195">This score combines course progress, attendance, tasks and trend participation.</p></div><div class="panel"><h3>Recommended next step</h3><p style="color:#748195">Complete the next live class, finish any pending tasks and review the latest creator trend tutorial.</p><button class="btn primary" data-dash="trends">Open Trends</button></div></div>`}
function studentEarnings(s){const rows=state.earnings.filter(e=>e.studentId===s.id).sort((a,b)=>b.date.localeCompare(a.date));const totals=earningSummary(s.id);return `<div class="subpage-head"><div><h1>Earnings</h1><p style="color:#748195">Approved payout credits assigned to your account.</p></div><button class="btn primary" data-dash="withdraw">Withdraw</button></div><div class="dash-card-grid"><div class="dash-card"><small>Available Balance</small><strong style="color:#059669">${money(s.available)}</strong></div><div class="dash-card"><small>Total Paid</small><strong>${money(s.paid)}</strong></div><div class="dash-card"><small>Last 7 Days</small><strong>${money(totals.week)}</strong></div><div class="dash-card"><small>Total Earnings</small><strong>${money(totals.lifetime)}</strong></div></div><div class="panel" style="margin-top:16px"><div class="notice">Dashboard earnings are approved payout credits. See the Earnings & Balance Policy for what this amount means.</div><div class="table-wrap" style="margin-top:13px"><table class="table"><thead><tr><th>Date</th><th>Program</th><th>Amount</th><th>Status</th></tr></thead><tbody>${rows.map(e=>`<tr><td>${niceDate(e.date)}</td><td>${esc(e.program)}</td><td class="amount green">${money(e.amount)}</td><td><span class="tag green">Approved</span></td></tr>`).join('')}</tbody></table></div></div>`}
function studentWithdraw(s){return `<div class="subpage-head"><div><h1>Withdraw</h1><p style="color:#748195">Request your available approved balance.</p></div></div><div class="dashboard-grid"><form class="panel" id="withdrawForm"><div class="panel-head"><h3>New withdrawal request</h3><span class="tag green">${money(s.available)} available</span></div><div class="field"><label>Amount</label><input required type="number" name="amount" min="0.01" step="0.01" max="${s.available}" value="${Number(s.available).toFixed(2)}" ${s.available<=0?'disabled':''}></div><div class="field"><label>Payout method</label><select name="method" id="payoutMethod"><option>JazzCash</option><option>Easypaisa</option><option>SadaPay</option><option>NayaPay</option><option>Bank Transfer</option></select></div><div class="field"><label>Account / IBAN / mobile number</label><input required name="account" value="${esc(s.payoutAccount||'')}" placeholder="Enter payout account"></div><div class="notice">Only request a payout to an account you control. Your dashboard balance is displayed in USD; local-wallet settlement may be converted during processing. Never share wallet PINs, OTPs or banking passwords.</div><button class="btn primary" style="margin-top:14px;width:100%" type="submit" ${s.available<=0?'disabled':''}>Request Withdrawal</button></form><div class="panel"><h3>Supported methods</h3><div class="bank-grid" style="margin-top:14px"><div class="bank-option"><span class="bank-logo jazz">JC</span><strong>JazzCash</strong></div><div class="bank-option"><span class="bank-logo easy">EP</span><strong>Easypaisa</strong></div><div class="bank-option"><span class="bank-logo sada">SD</span><strong>SadaPay</strong></div><div class="bank-option"><span class="bank-logo naya">NP</span><strong>NayaPay</strong></div><div class="bank-option"><span class="bank-logo bank">PK</span><strong>Bank Transfer</strong></div></div><p style="color:#748195;margin-top:18px">${esc(state.settings.weeklyUpdateText)}</p></div></div>`}
function studentPayments(s){const rows=state.withdrawals.filter(w=>w.studentId===s.id).sort((a,b)=>b.date.localeCompare(a.date));return `<div class="subpage-head"><div><h1>Payment History</h1><p style="color:#748195">Withdrawal requests and completed payments.</p></div></div><div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Request Date</th><th>Amount</th><th>Method</th><th>Status</th><th>Reference</th></tr></thead><tbody>${rows.map(w=>`<tr><td>${esc(w.id)}</td><td>${niceDate(w.date)}</td><td>${money(w.amount)}</td><td>${esc(w.method)}</td><td><span class="tag ${w.status==='Paid'?'green':w.status==='Rejected'?'red':'orange'}">${esc(w.status)}</span></td><td>${esc(w.reference||'—')}</td></tr>`).join('')||'<tr><td colspan="6">No payment history.</td></tr>'}</tbody></table></div></div>`}
function studentNotifications(s){const rows=state.notifications.filter(n=>n.studentId===s.id).sort((a,b)=>b.date.localeCompare(a.date));return `<div class="subpage-head"><div><h1>Notifications</h1><p style="color:#748195">Earnings, trends, classes and payment updates.</p></div><button class="btn light" data-action="mark-notifications">Mark all read</button></div><div class="list">${rows.map(n=>`<div class="list-item" style="background:${n.read?'#fff':'#f5f3ff'}"><div class="meta"><strong>${esc(n.title)}</strong><small>${niceDate(n.date)} · ${esc(n.body)}</small></div>${n.read?'':'<span class="tag green">New</span>'}</div>`).join('')||'<div class="empty">No notifications.</div>'}</div>`}
function studentProfile(s){return `<div class="subpage-head"><div><h1>Profile</h1><p style="color:#748195">Your account and payout details.</p></div></div><form class="panel" id="profileForm"><div class="profile-grid"><div class="field"><label>Full name</label><input name="name" value="${esc(s.name)}"></div><div class="field"><label>Email</label><input name="email" value="${esc(s.email)}" disabled></div><div class="field"><label>Phone</label><input name="phone" value="${esc(s.phone)}"></div><div class="field"><label>City</label><input name="city" value="${esc(s.city||'')}"></div><div class="field"><label>Preferred payout method</label><select name="payoutMethod">${['JazzCash','Easypaisa','SadaPay','NayaPay','Bank Transfer'].map(x=>`<option ${s.payoutMethod===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Payout account</label><input name="payoutAccount" value="${esc(s.payoutAccount||'')}"></div></div><div class="field"><label>About</label><textarea name="bio" rows="4">${esc(s.bio||'')}</textarea></div><button class="btn primary" type="submit">Save Profile</button></form>`}
function studentSupport(s=currentStudent()){const tickets=(state.supportMessages||[]).filter(x=>x.studentId===s.id);return `<div class="subpage-head"><div><h1>Support</h1><p style="color:#748195">Get help with your account, classes or payout request.</p></div></div><div class="dashboard-grid"><form class="panel" id="supportForm"><h3>Create Support Ticket</h3><div class="field"><label>Topic</label><select name="topic"><option>Account Help</option><option>Course / Class</option><option>Earnings / Payout</option><option>Technical Issue</option></select></div><div class="field"><label>Message</label><textarea required name="message" rows="5" placeholder="Describe your issue clearly"></textarea></div><button class="btn primary" type="submit">Submit Ticket</button></form><div class="panel"><h3>Support & safety</h3><p style="color:#748195">Email: ${esc(state.settings.supportEmail)}<br>WhatsApp: ${esc(state.settings.supportWhatsApp)}</p><div class="notice">Support will never ask for your JazzCash/Easypaisa PIN, OTP, card CVV or online banking password.</div><div class="list" style="margin-top:14px">${tickets.slice(0,3).map(t=>`<div class="list-item"><div class="meta"><strong>${esc(t.topic)}</strong><small>${niceDate(t.date)}</small></div><span class="tag orange">${esc(t.status)}</span></div>`).join('')||'<div class="empty">No support tickets yet.</div>'}</div></div></div>`}

function adminSidebar(){const items=[['overview','🏠 Overview'],['students','👥 Students'],['courses','📚 Courses'],['live','🎥 Live Classes'],['programs','🧩 Programs'],['trends','🔥 Trends'],['earnings','💰 Earnings'],['withdrawals','🏦 Withdrawals'],['notifications','🔔 Notify'],['support','💬 Support'],['settings','⚙️ Settings']];return `<aside class="sidebar"><div class="side-profile"><strong>${esc(state.admin.name)}</strong><small>Super Admin · Full Access</small></div><div class="side-nav">${items.map(([id,l])=>`<button class="${adminView===id?'active':''}" data-admin="${id}">${l}</button>`).join('')}<button data-action="logout">↩ Logout</button></div></aside>`}
function adminDashboard(){if(!state.session||state.session.role!=='admin'){openAuth('login');location.hash='#/';return homePage()}return `<div class="dashboard-page"><div class="dashboard-shell">${adminSidebar()}<section class="dashboard-main" id="adminContent">${adminPanel()}</section></div></div>`}
function adminPanel(){
 if(adminView==='students') return adminStudents(); if(adminView==='courses') return adminCourses(); if(adminView==='live') return adminLive(); if(adminView==='programs') return adminPrograms(); if(adminView==='trends') return adminTrends(); if(adminView==='earnings') return adminEarnings(); if(adminView==='withdrawals') return adminWithdrawals(); if(adminView==='notifications') return adminNotify(); if(adminView==='support') return adminSupport(); if(adminView==='settings') return adminSettings();
 const pending=state.withdrawals.filter(w=>w.status==='Pending').length,totalPaid=state.withdrawals.filter(w=>w.status==='Paid').reduce((a,b)=>a+b.amount,0);return `<div class="admin-banner"><span class="kicker" style="color:#a7f3ff">Admin Control Center</span><h1 style="margin:8px 0 6px">Mughees Edtior Platform</h1><p>Manage students, classes, programs, approved earnings, payout requests and notifications.</p></div><div class="admin-stats"><div class="dash-card"><small>Total Students</small><strong>${state.students.length}</strong></div><div class="dash-card"><small>Active Programs</small><strong>${(state.programs||[]).filter(p=>p.status==='Active').length}</strong></div><div class="dash-card"><small>Pending Withdrawals</small><strong>${pending}</strong></div><div class="dash-card"><small>Recorded Paid Amount</small><strong>${money(totalPaid)}</strong></div></div><div class="dashboard-grid"><div class="panel"><div class="panel-head"><h3>Students</h3><button class="btn small light" data-admin="students">Manage</button></div><div class="list">${state.students.map(s=>`<div class="list-item"><div class="meta"><strong>${esc(s.name)}</strong><small>${esc(s.id)} · ${esc(s.program)}</small></div><span class="amount green">${money(s.available)}</span></div>`).join('')}</div></div><div class="panel"><div class="panel-head"><h3>Upcoming classes</h3><button class="btn small light" data-admin="live">Manage</button></div><div class="list">${state.classes.filter(c=>c.status==='Upcoming').map(c=>`<div class="list-item"><div class="meta"><strong>${esc(c.title)}</strong><small>${niceDate(c.date)} · ${esc(c.time)}</small></div></div>`).join('')}</div></div></div>`
}
function adminStudents(){return `<div class="subpage-head"><div><h1>Students</h1><p style="color:#748195">Private accounts, progress, performance and balances.</p></div></div><div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>Student</th><th>Program</th><th>Progress</th><th>Performance</th><th>Available</th><th>Paid</th><th>Action</th></tr></thead><tbody>${state.students.map(s=>`<tr><td><strong>${esc(s.name)}</strong><br><small>${esc(s.id)}</small></td><td>${esc(s.program)}</td><td>${s.progress}%</td><td>${esc(s.performance)}</td><td>${money(s.available)}</td><td>${money(s.paid)}</td><td><button class="btn small light" data-action="view-student" data-id="${s.id}">View</button></td></tr>`).join('')}</tbody></table></div></div>`}
function adminCourses(){return `<div class="subpage-head"><div><h1>Courses</h1><p style="color:#748195">Manage curriculum, modules and student learning paths.</p></div></div><div class="cards">${state.courses.map(c=>`<div class="card"><span class="pill">${c.lessons} modules</span><h3 style="margin-top:14px">${esc(c.title)}</h3><p>${esc(c.desc)}</p><ul class="feature-list">${c.modules.map(m=>`<li>${esc(m)}</li>`).join('')}</ul><button class="btn light" data-action="edit-course" data-id="${c.id}">Edit Course</button></div>`).join('')}</div>`}
function adminLive(){return `<div class="subpage-head"><div><h1>Live Classes</h1><p style="color:#748195">Schedule classes and publish recordings.</p></div><button class="btn primary" data-action="add-class">+ Add Class</button></div><div class="panel"><table class="table"><thead><tr><th>Class</th><th>Date</th><th>Time</th><th>Trainer</th><th>Status</th></tr></thead><tbody>${state.classes.map(c=>`<tr><td>${esc(c.title)}</td><td>${niceDate(c.date)}</td><td>${esc(c.time)}</td><td>${esc(c.trainer)}</td><td><span class="tag ${c.status==='Upcoming'?'orange':'green'}">${esc(c.status)}</span></td></tr>`).join('')}</tbody></table></div>`}
function adminPrograms(){return `<div class="subpage-head"><div><h1>Creator Programs</h1><p style="color:#748195">Manage current programs and add future creator apps.</p></div><button class="btn primary" data-action="add-program">+ Add Program</button></div><div class="cards">${(state.programs||[]).map(p=>`<div class="card"><div class="icon-tile">${esc(p.code||p.name.slice(0,2).toUpperCase())}</div><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p><span class="tag green">${esc(p.status||'Active')}</span></div>`).join('')}</div>`}
function adminTrends(){return `<div class="subpage-head"><div><h1>Trend Updates</h1><p style="color:#748195">Publish trends and notify students.</p></div><button class="btn primary" data-action="add-trend">+ Add Trend</button></div><div class="panel"><table class="table"><thead><tr><th>Program</th><th>Trend</th><th>Added</th><th>Difficulty</th><th>Status</th></tr></thead><tbody>${state.trends.map(t=>`<tr><td>${esc(t.program)}</td><td>${esc(t.title)}</td><td>${niceDate(t.added)}</td><td>${esc(t.difficulty)}</td><td><span class="tag ${t.status==='New'?'green':''}">${esc(t.status)}</span></td></tr>`).join('')}</tbody></table></div>`}
function adminEarnings(){return `<div class="subpage-head"><div><h1>Earnings Management</h1><p style="color:#748195">Add student-visible approved payout credits. Optional source/accounting notes remain Admin-only.</p></div></div><div class="dashboard-grid"><form class="panel" id="addEarningForm"><h3>Add approved earning</h3><div class="field"><label>Student</label><select name="studentId">${state.students.map(s=>`<option value="${s.id}">${esc(s.name)} (${s.id})</option>`).join('')}</select></div><div class="field"><label>Program</label><select name="program"><option>Hypic</option><option>CapCut</option><option>TikTok Creator</option><option>Future App</option></select></div><div class="field"><label>Approved payout credit (student-visible)</label><input required type="number" min="0.01" step="0.01" name="amount" placeholder="25.00"></div><div class="field"><label>Source gross / partner report (Admin-only, optional)</label><input type="number" min="0" step="0.01" name="internalGross" placeholder="Internal record only"></div><div class="field"><label>Internal note</label><textarea name="note" rows="3" placeholder="Weekly creator report"></textarea></div><button class="btn primary" type="submit">Add Earning & Notify Student</button></form><div class="panel"><h3>Recent credits</h3><div class="list" style="margin-top:14px">${state.earnings.slice().reverse().slice(0,8).map(e=>{const s=state.students.find(x=>x.id===e.studentId);return `<div class="list-item"><div class="meta"><strong>${esc(s?.name||e.studentId)} · ${esc(e.program)}</strong><small>${niceDate(e.date)}</small></div><span class="amount green">${money(e.amount)}</span></div>`}).join('')}</div></div></div>`}
function adminWithdrawals(){const rows=state.withdrawals.slice().sort((a,b)=>b.date.localeCompare(a.date));return `<div class="subpage-head"><div><h1>Withdrawals</h1><p style="color:#748195">Review, pay, reject and record transaction references.</p></div></div><div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>Student</th><th>Amount</th><th>Method</th><th>Account</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(w=>{const s=state.students.find(x=>x.id===w.studentId);return `<tr><td>${esc(s?.name||w.studentId)}</td><td>${money(w.amount)}</td><td>${esc(w.method)}</td><td>${esc(w.account)}</td><td>${niceDate(w.date)}</td><td><span class="tag ${w.status==='Paid'?'green':w.status==='Rejected'?'red':'orange'}">${esc(w.status)}</span></td><td>${w.status==='Pending'?`<button class="btn small primary" data-action="pay-withdrawal" data-id="${w.id}">Mark Paid</button> <button class="btn small danger" data-action="reject-withdrawal" data-id="${w.id}">Reject</button>`:'—'}</td></tr>`}).join('')||'<tr><td colspan="7">No withdrawal requests.</td></tr>'}</tbody></table></div></div>`}
function adminNotify(){return `<div class="subpage-head"><div><h1>Send Notification</h1><p style="color:#748195">Message one student or all students.</p></div></div><form class="panel" id="notifyForm"><div class="field"><label>Recipient</label><select name="studentId"><option value="all">All Students</option>${state.students.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>Title</label><input required name="title" placeholder="New trend added"></div><div class="field"><label>Message</label><textarea required name="body" rows="4" placeholder="Your message"></textarea></div><button class="btn primary" type="submit">Send Notification</button></form>`}
function adminSupport(){const rows=(state.supportMessages||[]).slice().sort((a,b)=>b.date.localeCompare(a.date));return `<div class="subpage-head"><div><h1>Support Inbox</h1><p style="color:#748195">Review student support tickets.</p></div></div><div class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Student</th><th>Topic</th><th>Message</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(t=>{const st=state.students.find(s=>s.id===t.studentId);return `<tr><td>${niceDate(t.date)}</td><td>${esc(st?.name||t.studentId)}</td><td>${esc(t.topic)}</td><td style="max-width:360px;white-space:normal">${esc(t.message)}</td><td><span class="tag ${t.status==='Resolved'?'green':'orange'}">${esc(t.status)}</span></td><td>${t.status!=='Resolved'?`<button class="btn small primary" data-action="resolve-ticket" data-id="${t.id}">Resolve</button>`:'—'}</td></tr>`}).join('')||'<tr><td colspan="6">No support tickets.</td></tr>'}</tbody></table></div></div>`}
function adminSettings(){return `<div class="subpage-head"><div><h1>Settings</h1><p style="color:#748195">Manage brand and support settings.</p></div><button class="btn danger" data-action="reset-demo">Reset Local Data</button></div><form class="panel" id="settingsForm"><div class="field"><label>Brand name</label><input name="brand" value="${esc(state.settings.brand)}"></div><div class="field"><label>Support email</label><input name="supportEmail" value="${esc(state.settings.supportEmail)}"></div><div class="field"><label>Support WhatsApp</label><input name="supportWhatsApp" value="${esc(state.settings.supportWhatsApp)}"></div><div class="field"><label>Weekly update wording</label><textarea name="weeklyUpdateText" rows="3">${esc(state.settings.weeklyUpdateText)}</textarea></div><button class="btn primary" type="submit">Save Settings</button><p class="micro" style="margin-top:12px;color:#748195">Sensitive settings should be protected with role-based access and audit logging in the live deployment.</p></form>`}

function showStudentModal(id){const s=state.students.find(x=>x.id===id);if(!s)return;const totals=earningSummary(s.id);$('#genericModalBody').innerHTML=`<button class="modal-close" data-action="close-modal">×</button><h2>${esc(s.name)}</h2><p style="color:#748195">${esc(s.id)} · ${esc(s.status)}</p><div class="profile-grid"><div class="profile-box"><small>Program</small><strong>${esc(s.program)}</strong></div><div class="profile-box"><small>Available</small><strong>${money(s.available)}</strong></div><div class="profile-box"><small>Progress</small><strong>${s.progress}%</strong></div><div class="profile-box"><small>Attendance</small><strong>${s.attendance}%</strong></div><div class="profile-box"><small>Total Earnings</small><strong>${money(totals.lifetime)}</strong></div><div class="profile-box"><small>Total Paid</small><strong>${money(s.paid)}</strong></div></div><div class="notice" style="margin-top:14px">Admin can manage credits, withdrawals, courses and notifications from the main admin sections.</div>`;$('#genericModal').classList.add('open');}
function addClassModal(){$('#genericModalBody').innerHTML=`<button class="modal-close" data-action="close-modal">×</button><h2>Add Live Class</h2><form id="classForm"><div class="field"><label>Title</label><input required name="title"></div><div class="field"><label>Trainer</label><input required name="trainer" value="Mughees"></div><div class="field"><label>Date</label><input required type="date" name="date"></div><div class="field"><label>Time</label><input required name="time" placeholder="8:00 PM"></div><div class="field"><label>Batch</label><input required name="batch" placeholder="Creator Batch 03"></div><div class="field"><label>Meeting / Recording URL (optional)</label><input type="url" name="link" placeholder="https://..."></div><button class="btn primary" type="submit">Create Class</button></form>`;$('#genericModal').classList.add('open');bindForms();}
function addTrendModal(){$('#genericModalBody').innerHTML=`<button class="modal-close" data-action="close-modal">×</button><h2>Add Trend Update</h2><form id="trendForm"><div class="field"><label>Program</label><select name="program"><option>TikTok</option><option>Hypic</option><option>CapCut</option><option>Future App</option></select></div><div class="field"><label>Trend title</label><input required name="title"></div><div class="field"><label>Difficulty</label><select name="difficulty"><option>Easy</option><option>Medium</option><option>Advanced</option></select></div><button class="btn primary" type="submit">Publish & Notify</button></form>`;$('#genericModal').classList.add('open');bindForms();}
function addProgramModal(){$('#genericModalBody').innerHTML=`<button class="modal-close" data-action="close-modal">×</button><h2>Add Creator Program</h2><p style="color:#748195">Create a new creator program and publish it across the platform.</p><form id="programForm"><div class="field"><label>Program name</label><input required name="name" placeholder="New Creator App"></div><div class="field"><label>Description</label><textarea required name="desc" rows="4"></textarea></div><button class="btn primary" type="submit">Save Program</button></form>`;$('#genericModal').classList.add('open');bindForms();}
function showInfoModal(title,body,actions=''){$('#genericModalBody').innerHTML=`<button class="modal-close" data-action="close-modal" aria-label="Close">×</button><h2>${esc(title)}</h2>${body}${actions}`;$('#genericModal').classList.add('open');bindGlobal();}
function showClassDetail(id){const c=state.classes.find(x=>x.id===id);if(!c)return;showInfoModal(c.title,`<p class="muted-copy">${niceDate(c.date)} · ${esc(c.time)} · ${esc(c.trainer)}</p><div class="profile-box"><small>Batch</small><strong>${esc(c.batch)}</strong></div><p class="muted-copy" style="margin-top:14px">${c.status==='Upcoming'?'Your class details are ready. When a meeting link is published, it will open from this screen.':'This session is marked as recorded. Add the recording URL from Admin to open it directly.'}</p>`,c.link&&c.link!=='#'?`<a class="btn primary" target="_blank" rel="noopener" href="${esc(c.link)}">${c.status==='Upcoming'?'Join Session':'Watch Recording'}</a>`:'');}
function showCourseDetail(id){const c=state.courses.find(x=>x.id===id);if(!c)return;showInfoModal(c.title,`<p class="muted-copy">${esc(c.desc)}</p><div class="module-stack">${c.modules.map((m,i)=>`<div class="module-row"><span>${String(i+1).padStart(2,'0')}</span><strong>${esc(m)}</strong></div>`).join('')}</div>`);}
function showTrendDetail(id){const t=state.trends.find(x=>x.id===id);if(!t)return;showInfoModal(t.title,`<p class="muted-copy">${esc(t.program)} · ${esc(t.difficulty)} · ${niceDate(t.added)}</p><div class="notice">Use this trend as a structured practice task. Review the hook, edit, caption and publishing checklist before posting.</div>`);}
function editCourseModal(id){const c=state.courses.find(x=>x.id===id);if(!c)return;$('#genericModalBody').innerHTML=`<button class="modal-close" data-action="close-modal">×</button><h2>Edit Course</h2><form id="courseEditForm"><input type="hidden" name="id" value="${esc(c.id)}"><div class="field"><label>Title</label><input required name="title" value="${esc(c.title)}"></div><div class="field"><label>Description</label><textarea required name="desc" rows="4">${esc(c.desc)}</textarea></div><div class="field"><label>Modules (one per line)</label><textarea required name="modules" rows="7">${esc(c.modules.join('\n'))}</textarea></div><button class="btn primary" type="submit">Save Course</button></form>`;$('#genericModal').classList.add('open');bindForms();}
function resolveTicket(id){const t=(state.supportMessages||[]).find(x=>x.id===id);if(!t)return;t.status='Resolved';notify(t.studentId,'Support ticket resolved',`Your ${t.topic} ticket has been marked resolved.`);save();render();toast('Support ticket resolved.');}
function payWithdrawal(id){const w=state.withdrawals.find(x=>x.id===id);if(!w||w.status!=='Pending'){toast('This withdrawal has already been processed.');return;}const ref=prompt('Enter payment reference / transaction ID:',`PAY-${Date.now().toString().slice(-6)}`);if(ref===null)return;w.status='Paid';w.paidDate=todayISO();w.reference=ref||'Recorded';const s=state.students.find(x=>x.id===w.studentId);if(s){s.paid+=w.amount;notify(s.id,'Withdrawal paid',`${money(w.amount)} has been marked as paid via ${w.method}.`)}save();render();toast('Withdrawal marked paid.');}
function rejectWithdrawal(id){const w=state.withdrawals.find(x=>x.id===id);if(!w||w.status!=='Pending'){toast('This withdrawal has already been processed.');return;}if(!confirm('Reject this withdrawal and return the reserved amount to the student balance?'))return;w.status='Rejected';const s=state.students.find(x=>x.id===w.studentId);if(s){s.available+=w.amount;notify(s.id,'Withdrawal rejected',`${money(w.amount)} has been returned to your available balance.`)}save();render();toast('Withdrawal rejected and balance restored.');}

function bindForms(){
 const login=$('#loginForm'); if(login)login.onsubmit=async e=>{e.preventDefault();const fd=new FormData(login),email=String(fd.get('email')).trim().toLowerCase(),pw=String(fd.get('password')); const {data,error}=await supabase.auth.signInWithPassword({email,password:pw}); if(error||!data){toast('Invalid email or password.');return;} if(email===state.admin.email){state.session={role:'admin'}; save(); closeModals(); location.hash='#/admin'; render(); return;} const s=state.students.find(x=>x.email.toLowerCase()===email); if(s){state.session={role:'student',studentId:s.id}; save(); closeModals(); location.hash='#/dashboard'; render();} else {toast('Student record not found.');} };
 const signup=$('#signupForm'); if(signup)signup.onsubmit=async e=>{e.preventDefault();const fd=new FormData(signup),email=String(fd.get('email')).trim().toLowerCase(),pw=String(fd.get('password')); if(state.students.some(x=>x.email.toLowerCase()===email)){toast('An account with this email already exists.');return} const {data,error}=await supabase.auth.signUp({email,password:pw}); if(error||!data){toast('Signup failed.');return} const s={id:uid('ST'),name:String(fd.get('name')).trim(),avatar:'',email,password:'',phone:String(fd.get('phone')).trim(),status:'Active Student',program:String(fd.get('program')),joinDate:todayISO(),today:0,week:0,month:0,lifetime:0,available:0,paid:0,attendance:100,progress:0,tasksDone:0,tasksTotal:20,trendParticipation:0,performance:'New',payoutMethod:'JazzCash',payoutAccount:'',city:'',bio:''}; state.students.push(s); state.session={role:'student',studentId:s.id}; save(); closeModals(); location.hash='#/dashboard'; render(); toast('Student account created.'); };
 const w=$('#withdrawForm'); if(w)w.onsubmit=e=>{e.preventDefault();const s=currentStudent(),fd=new FormData(w),amt=Number(fd.get('amount')),method=String(fd.get('method')),account=String(fd.get('account')).trim();if(!amt||amt<0.01||amt>s.available){toast('Enter an amount within your available balance.');return}if(!account){toast('Enter your payout account.');return}s.available-=amt;s.payoutMethod=method;s.payoutAccount=account;state.withdrawals.unshift({id:uid('WD'),studentId:s.id,date:todayISO(),amount:amt,method,account,status:'Pending',paidDate:'',reference:''});notify(s.id,'Withdrawal submitted',`${money(amt)} withdrawal request is pending review.`);save();dashView='payments';render();toast('Withdrawal request submitted.');};
 const pf=$('#profileForm');if(pf)pf.onsubmit=e=>{e.preventDefault();const s=currentStudent(),fd=new FormData(pf);['name','phone','city','payoutMethod','payoutAccount','bio'].forEach(k=>s[k]=String(fd.get(k)||''));save();toast('Profile saved.');render();};
 const ef=$('#addEarningForm');if(ef)ef.onsubmit=e=>{e.preventDefault();const fd=new FormData(ef),sid=String(fd.get('studentId')),amt=Number(fd.get('amount')),program=String(fd.get('program')),s=state.students.find(x=>x.id===sid);if(!s||!amt)return;state.earnings.unshift({id:uid('E'),studentId:sid,date:todayISO(),program,amount:amt,note:String(fd.get('note')||''),internalGross:Number(fd.get('internalGross')||0)});s.lifetime=Number(s.lifetime||0)+amt;s.available+=amt;notify(sid,'New earnings added',`${money(amt)} has been added to your approved account balance.`);save();render();toast('Earning added and student notified.');};
 const nf=$('#notifyForm');if(nf)nf.onsubmit=e=>{e.preventDefault();const fd=new FormData(nf),sid=String(fd.get('studentId')),title=String(fd.get('title')),body=String(fd.get('body'));if(sid==='all')state.students.forEach(s=>notify(s.id,title,body));else notify(sid,title,body);save();toast('Notification sent.');nf.reset();};
 const sf=$('#settingsForm');if(sf)sf.onsubmit=e=>{e.preventDefault();const fd=new FormData(sf);['brand','supportEmail','supportWhatsApp','weeklyUpdateText'].forEach(k=>state.settings[k]=String(fd.get(k)||''));save();toast('Settings saved.');};
 const sup=$('#supportForm');if(sup)sup.onsubmit=e=>{e.preventDefault();const fd=new FormData(sup),st=currentStudent();state.supportMessages=state.supportMessages||[];state.supportMessages.unshift({id:uid('SUP'),studentId:st.id,topic:String(fd.get('topic')),message:String(fd.get('message')),date:todayISO(),status:'Open'});save();render();toast('Support ticket submitted.');};
 const cef=$('#courseEditForm');if(cef)cef.onsubmit=e=>{e.preventDefault();const fd=new FormData(cef),c=state.courses.find(x=>x.id===String(fd.get('id')));if(!c)return;c.title=String(fd.get('title')).trim();c.desc=String(fd.get('desc')).trim();c.modules=String(fd.get('modules')).split('\n').map(x=>x.trim()).filter(Boolean);c.lessons=c.modules.length;save();closeModals();render();toast('Course updated.');};
 const cf=$('#classForm');if(cf)cf.onsubmit=e=>{e.preventDefault();const fd=new FormData(cf);state.classes.unshift({id:uid('CL'),title:String(fd.get('title')),trainer:String(fd.get('trainer')),date:String(fd.get('date')),time:String(fd.get('time')),batch:String(fd.get('batch')),status:'Upcoming',link:String(fd.get('link')||'#')});state.students.forEach(s=>notify(s.id,'New live class scheduled',`${String(fd.get('title'))} is scheduled for ${niceDate(String(fd.get('date')))}.`));save();closeModals();render();toast('Class added and students notified.');};
 const tf=$('#trendForm');if(tf)tf.onsubmit=e=>{e.preventDefault();const fd=new FormData(tf),t={id:uid('TR'),program:String(fd.get('program')),title:String(fd.get('title')),added:todayISO(),difficulty:String(fd.get('difficulty')),status:'New'};state.trends.unshift(t);state.students.forEach(s=>notify(s.id,'New creator trend',`${t.program}: ${t.title}`));save();closeModals();render();toast('Trend published and students notified.');};
 const prf=$('#programForm');if(prf)prf.onsubmit=e=>{e.preventDefault();const fd=new FormData(prf),name=String(fd.get('name')).trim(),desc=String(fd.get('desc')).trim();state.programs=state.programs||[];state.programs.push({id:uid('PG'),name,desc,code:name.slice(0,2).toUpperCase(),status:'Active'});save();closeModals();render();toast('Program added.');};
 const contact=$('#contactForm');if(contact)contact.onsubmit=e=>{e.preventDefault();const fd=new FormData(contact);state.contactMessages=state.contactMessages||[];state.contactMessages.unshift({id:uid('MSG'),name:String(fd.get('name')),email:String(fd.get('email')),message:String(fd.get('message')),date:todayISO()});save();contact.reset();toast('Message submitted to support.');};
const fp=$('#forgotPasswordForm');if(fp)fp.onsubmit=async e=>{e.preventDefault();const fd=new FormData(fp),email=String(fd.get('email')).trim().toLowerCase();const {data,error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:'https://mugees-editor.vercel.app/?reset=1'});if(error){toast(error.message||'Failed to send reset email');}else{toast('Password reset email sent');closeModals();}};
const rp=$('#resetPasswordForm');if(rp)rp.onsubmit=async e=>{e.preventDefault();const fd=new FormData(rp),pw=String(fd.get('password')),cp=String(fd.get('confirm'));if(pw.length<8){var er=document.getElementById('rp_err');if(er)er.textContent='Password must be at least 8 characters.';toast('Password must be at least 8 characters.');return;}if(pw!==cp){var er=document.getElementById('rp_err');if(er)er.textContent='Passwords do not match.';toast('Passwords do not match.');return;}var er=document.getElementById('rp_err');if(er)er.textContent='';const {data,error}=await supabase.auth.updateUser({password:pw});if(error){toast(error.message||'Failed to reset password');}else{toast('Password updated');closeModals();openAuth('login');}};
 $$('[data-action=\"toggle-eye\"]').forEach(function(btn){btn.onclick=function(){var t=document.getElementById(btn.dataset.target);if(t)t.type=t.type==='password'?'text':'password';};});
}

function bindGlobal(){
 $$('[data-action]').forEach(el=>el.onclick=e=>{const a=el.dataset.action,id=el.dataset.id;if(a==='open-login')openAuth('login');else if(a==='open-signup')openAuth('signup');else if(a==='open-forgot-password')openForgotPassword();else if(a==='toggle-eye'){var t=document.getElementById(el.dataset.target);if(t)t.type=t.type==='password'?'text':'password';}else if(a==='close-modal')closeModals();else if(a==='logout'){state.session=null;save();dashView='overview';adminView='overview';$('#mobileMenu').classList.remove('open');location.hash='#/';render();}else if(a==='mark-notifications'){const s=currentStudent();state.notifications.forEach(n=>{if(n.studentId===s.id)n.read=true});save();render();}else if(a==='view-student')showStudentModal(id);else if(a==='add-class')addClassModal();else if(a==='add-trend')addTrendModal();else if(a==='add-program')addProgramModal();else if(a==='pay-withdrawal')payWithdrawal(id);else if(a==='reject-withdrawal')rejectWithdrawal(id);else if(a==='resolve-ticket')resolveTicket(id);else if(a==='reset-demo'){if(confirm('Reset all local data?'))resetDemo();}else if(a==='class-detail')showClassDetail(id);else if(a==='course-detail')showCourseDetail(id);else if(a==='trend-detail')showTrendDetail(id);else if(a==='edit-course')editCourseModal(id);});
 $$('[data-dash]').forEach(el=>el.onclick=()=>{
  dashView=el.dataset.dash;
  $('#mobileMenu').classList.remove('open');
  if(route()!=='dashboard'){location.hash='#/dashboard';render();}else{render();}
 });
 $$('[data-admin]').forEach(el=>el.onclick=()=>{adminView=el.dataset.admin;render();});
 $$('[data-auth-tab]').forEach(el=>el.onclick=()=>openAuth(el.dataset.authTab));
 $$('[data-faq]').forEach(el=>el.onclick=()=>el.closest('.faq').classList.toggle('open'));
 bindForms();
}

function syncHeader(){
 const actions=$('.nav-actions'); if(!actions)return;
 const mobileMenu=$('#mobileMenu');
 if(state.session?.role==='student'){
   actions.innerHTML=`<button class="icon-btn mobile-menu-btn" id="mobileMenuBtn" aria-label="Open menu" aria-expanded="false">☰</button><a class="btn ghost" href="#/dashboard" id="headerDashBtn">Dashboard</a><button class="btn primary" data-action="logout" id="headerLogoutBtn">Logout</button>`;
   if(mobileMenu) mobileMenu.innerHTML=`<a href="#/" data-route="home">Home</a><a href="#/courses" data-route="courses">Courses</a><a href="#/programs" data-route="programs">Creator Programs</a><a href="#/live" data-route="live">Live Classes</a><a href="#/dashboard" id="mobileDashBtn">Dashboard</a><a href="#/how-it-works" data-route="how-it-works">How It Works</a><a href="#/faq" data-route="faq">FAQ</a><button class="mobile-nav-btn" data-dash="notifications" id="mobileNotifBtn">🔔 Notifications</button><button class="mobile-nav-btn" data-dash="profile" id="mobileProfileBtn">👤 Profile</button><button class="mobile-nav-btn mobile-logout-btn" data-action="logout" id="mobileLogoutBtn">↩ Logout</button>`;
 }else if(state.session?.role==='admin'){
   actions.innerHTML=`<button class="icon-btn mobile-menu-btn" id="mobileMenuBtn" aria-label="Open menu" aria-expanded="false">☰</button><a class="btn ghost" href="#/admin" id="headerAdminBtn">Admin Dashboard</a><button class="btn primary" data-action="logout" id="headerLogoutBtn">Logout</button>`;
   if(mobileMenu) mobileMenu.innerHTML=`<a href="#/" data-route="home">Home</a><a href="#/courses" data-route="courses">Courses</a><a href="#/programs" data-route="programs">Creator Programs</a><a href="#/live" data-route="live">Live Classes</a><a href="#/admin" id="mobileAdminBtn">Admin Dashboard</a><a href="#/how-it-works" data-route="how-it-works">How It Works</a><a href="#/faq" data-route="faq">FAQ</a><a href="#/contact" data-route="contact">Contact</a><button class="mobile-nav-btn mobile-logout-btn" data-action="logout" id="mobileAdminLogoutBtn">↩ Logout</button>`;
 }else{
   actions.innerHTML=`<button class="icon-btn mobile-menu-btn" id="mobileMenuBtn" aria-label="Open menu" aria-expanded="false">☰</button><button class="btn ghost" data-action="open-login" id="headerLoginBtn">Login</button><button class="btn primary" data-action="open-signup" id="headerJoinBtn">Join Now</button>`;
   if(mobileMenu) mobileMenu.innerHTML=`<a href="#/" data-route="home">Home</a><a href="#/courses" data-route="courses">Courses</a><a href="#/programs" data-route="programs">Creator Programs</a><a href="#/live" data-route="live">Live Classes</a><a href="#/how-it-works" data-route="how-it-works">How It Works</a><a href="#/faq" data-route="faq">FAQ</a><a href="#/contact" data-route="contact">Contact</a><button class="mobile-nav-btn" data-action="open-login" id="mobileLoginBtn">Login</button><button class="mobile-nav-btn mobile-join-btn" data-action="open-signup" id="mobileJoinBtn">Join Now</button>`;
 }
 const mb=$('#mobileMenuBtn');if(mb)mb.onclick=()=>{const menu=$('#mobileMenu'),open=menu.classList.toggle('open');mb.setAttribute('aria-expanded',String(open));};
}
function route(){const r=(location.hash||'#/').replace(/^#\//,'').split('?')[0];return r||'home'}
function render(){syncHeader();const r=route();const app=$('#app');$('#year').textContent=new Date().getFullYear();$('#siteFooter').classList.toggle('hidden',r==='dashboard'||r==='admin');let html='';switch(r){case'home':html=homePage();break;case'courses':html=coursesPage();break;case'programs':html=programsPage();break;case'live':html=livePage();break;case'how-it-works':html=howPage();break;case'faq':html=faqPage();break;case'contact':html=contactPage();break;case'dashboard':html=studentDashboard();break;case'admin':html=adminDashboard();break;case'terms':case'privacy':case'payout-policy':case'refund-policy':case'earnings-policy':case'earnings-disclaimer':case'community-guidelines':html=legalPage(r);break;default:html=`${pageHero('Page not found','The page you requested does not exist.')}<section class="section"><a class="btn primary" href="#/">Back Home</a></section>`}app.innerHTML=html;bindGlobal();window.scrollTo({top:0,behavior:'instant'});}

window.addEventListener('hashchange',()=>{$('#mobileMenu').classList.remove('open');render();});
window.addEventListener('click',e=>{if(e.target.classList.contains('modal'))closeModals();});
render();
// Listen for Supabase auth state changes for password recovery
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'PASSWORD_RECOVERY') {
    openResetPassword();
  }
});
// On page load, if URL contains reset query, open reset password modal
if (new URLSearchParams(location.search).has('reset')) {
  supabase.auth.getSession().then(function(res) {
    if (res.data && res.data.session) {
      openResetPassword();
    } else {
      $('#authModal').classList.add('open');
      $('#authModal').setAttribute('aria-hidden','false');
      $('#authBody').innerHTML = '<h2>Invalid reset link</h2><p style="color:#728096">This password reset link is invalid or has expired. Please request a new one.</p><a href="#" data-action="open-forgot-password" style="color:#3b82f6">Request a new reset email</a>';
      bindGlobal();
    }
  });
}
